name: code-format-checks
on:
    push:
        branches:
            - dev_branch
jobs:
    formatting-checks:
        runs-on: ubuntu-latest
        container:
            image: finanssoreal/node-prettier
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Check JS file formatting
              if: always()
              run: prettier . --check